all:
  hosts:
    kos11:
      ansible_host: 192.168.66.33
      ip: 192.168.66.33
      access_ip: 192.168.66.33
  children:
    kube_control_plane:
      hosts:
        kos11:
    kube_node:
      hosts:
        kos11:
    etcd:
      hosts:
        kos11:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
